### ISSUE TITLE
double check list for milestone 2

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/gradecalculatorpy#30]
Tasks: 

- [x] Add a one-line docstring in ALL the test functions we define! @CChCheChen 
- [x] Unit tests: 3-5 cases each. @CChCheChen 
- [x] Make sure that the tests cover all branches (e.g., if your function has an if statement, you should have tests where the if statement is true, and where the if statement is false.)
- [x] pytest for ALL 
- [x] Finish function writing
- [x] Finish R package docstring and review the PR
- [x] Final review, create release and submit

**Comment by CChCheChen** [comment]
First 2 check points are done per [Pull Request](https://github.com/UBC-MDS/gradecalculatorpy/pull/31).
Please review, approve and update the checklist
