### ISSUE TITLE
Milestone 1 for Edward

### ISSUE THREAD

**Issue by yukunzGIT** [UBC-MDS/gradecalculatorpy#9]
Tasks: 
- [x] Define function 3: predict_final.py
- [x] Update CONTRIBUTORS section in the README.md
- [x] Edit CONDUCT.md
- [x] Edit CONTRIBUTING.md
- [x] Final review, create release, paste TEAMWORK CONTRACT and submit
